### ISSUE TITLE
The appUrl in loadEmberApp is useless

### ISSUE THREAD

**Issue by ericmackrodt** [CanopyTax/single-spa-ember#1]
It's only checked to see if the user passed it, but it's never called after that.

**Comment by internettrans** [comment]
Oops that's embarrassing. Good point. I originally wrote this for https://github.com/CanopyTax/single-spa-examples/pull/37 and it maybe ended up a little too specific to that one use case, instead of generic like I was hoping.

Thinking about `appUrl`, I'm not sure if it makes a lot of sense because we need to load the vendor bundle and the app bundle which are at two different urls. Do you think it would be better to have`vendorUrl`, `appUrl`, and `appName`? (And actually use the urls instead of ignoring them 😄 )

**Comment by internettrans** [comment]
Fixed and released as single-spa-ember@0.1.6
